# Generated by Django 2.0.3 on 2018-03-13 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdl_name', models.CharField(max_length=200)),
                ('mdl_description', models.CharField(max_length=200)),
                ('mdl_url', models.CharField(max_length=200)),
                ('mdl_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_name', models.CharField(max_length=200)),
                ('rol_description', models.CharField(max_length=200)),
                ('rol_url', models.CharField(max_length=200)),
                ('rol_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role_Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emisora.Role')),
                ('rol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emisora.Module')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_name', models.CharField(max_length=200)),
                ('usr_lastname', models.CharField(max_length=200)),
                ('usr_celphone', models.CharField(max_length=200)),
                ('usr_password', models.CharField(max_length=200)),
                ('usr_created_by', models.CharField(max_length=200)),
                ('usr_modified_by', models.CharField(max_length=200)),
                ('usr_created_date', models.DateTimeField(verbose_name='Creado')),
                ('usr_modified_date', models.DateTimeField(verbose_name='Editado')),
                ('usr_enabled', models.BooleanField(default=True)),
                ('rol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emisora.Role')),
            ],
        ),
    ]
