# Generated by Django 2.0.4 on 2018-04-17 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emisora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_module',
            name='mdl_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emisora.Module'),
        ),
        migrations.AlterField(
            model_name='role_module',
            name='rol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emisora.Role'),
        ),
    ]
