# Generated by Django 2.0.3 on 2018-04-18 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emisora', '0002_auto_20180416_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctg_name', models.CharField(max_length=100)),
                ('ctg_description', models.CharField(max_length=100)),
                ('ctg_image_url', models.CharField(max_length=250)),
                ('ctg_modified_date', models.DateTimeField(verbose_name='Editado')),
                ('ctg_created_date', models.DateTimeField(verbose_name='Creado')),
                ('ctg_created_by', models.CharField(max_length=200)),
                ('ctg_modified_by', models.CharField(max_length=200)),
                ('ctg_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sct_name', models.CharField(max_length=100)),
                ('sct_description', models.CharField(max_length=100)),
                ('sct_image_url', models.CharField(max_length=250)),
                ('sct_modified_date', models.DateTimeField(verbose_name='Editado')),
                ('sct_created_date', models.DateTimeField(verbose_name='Creado')),
                ('sct_created_by', models.CharField(max_length=200)),
                ('sct_modified_by', models.CharField(max_length=200)),
                ('sct_enabled', models.BooleanField(default=True)),
                ('ctg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emisora.Category')),
            ],
        ),
    ]
