# Generated by Django 2.0.3 on 2018-05-07 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emisora', '0004_auto_20180504_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prg_name', models.CharField(max_length=100)),
                ('prg_description', models.CharField(max_length=100)),
                ('prg_audio_url', models.CharField(max_length=250)),
                ('prg_image_url', models.CharField(max_length=250)),
                ('prg_modified_date', models.DateTimeField(editable=False, verbose_name='Editado')),
                ('prg_created_date', models.DateTimeField(editable=False, verbose_name='Creado')),
                ('prg_created_by', models.CharField(editable=False, max_length=200)),
                ('prg_modified_by', models.CharField(editable=False, max_length=200)),
                ('prg_enabled', models.BooleanField(default=True)),
                ('sct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emisora.Subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_start_time', models.DateTimeField(verbose_name='Inicio')),
                ('sp_end_time', models.DateTimeField(verbose_name='Final')),
                ('prg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emisora.Program')),
            ],
        ),
    ]
