# Generated by Django 2.0.3 on 2018-05-19 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emisora', '0006_auto_20180506_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('habilitado', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Editado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField(editable=False, null=True, verbose_name='Inicio')),
                ('fecha_final', models.DateTimeField(editable=False, null=True, verbose_name='Fin')),
                ('imagen_banner', models.ImageField(blank=True, default='categorias/sin-imagen.jpg', null=True, upload_to='categorias/')),
                ('tipo_programa', models.CharField(choices=[('pregrabado', 'Pregrabado'), ('en_vivo', 'En Vivo')], max_length=11)),
                ('url_pregrabado', models.CharField(max_length=200)),
                ('habilitado', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Editado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('habilitado', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Editado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emisora.Categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='sct_id',
        ),
        migrations.RemoveField(
            model_name='role_module',
            name='mdl_id',
        ),
        migrations.RemoveField(
            model_name='role_module',
            name='rol_id',
        ),
        migrations.RemoveField(
            model_name='schedule_program',
            name='prg_id',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='ctg_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rol_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Role_Module',
        ),
        migrations.DeleteModel(
            name='Schedule_program',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='creado_por',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='modificado_por',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programa',
            name='creado_por',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='programa_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programa',
            name='modificado_por',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='programa_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programa',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emisora.Subcategoria'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='creado_por',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='modificado_por',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
