# Generated by Django 2.0.3 on 2018-05-19 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emisora', '0007_auto_20180519_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cat_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='modificado_por',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cat_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programa',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='programa_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programa',
            name='modificado_por',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='programa_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='subcat_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='modificado_por',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='subcat_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
