# Generated by Django 2.0.3 on 2018-05-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisora', '0008_auto_20180519_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='url_pregrabado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
