# Generated by Django 2.0.3 on 2018-05-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emisora', '0009_auto_20180519_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='modificado_por',
        ),
    ]
