# Generated by Django 2.0.3 on 2018-05-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisora', '0010_auto_20180519_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='imagen_banner',
            field=models.ImageField(blank=True, default='media/img/programas/sin-imagen.jpg', null=True, upload_to='media/img/programas/'),
        ),
    ]
