# Generated by Django 2.0.3 on 2018-05-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisora', '0011_auto_20180519_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='url_pregrabado',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
